# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0342b14faf23976f31ac75fad8d975ee694549ef096638c0360f526d48221b6a65d3ec7d053e6dc5792581c6bba0fbed3e33d7e647d480c1b71c32a54fcb2445

test:
  secret_key_base: cdd6994b2e4239a25b9c5eebbed723aada95e8cee0ac79d5767ca6f518e0942177e57bf8d9069bc330054df1bffc8a6bcd1c80d1173a46ff14a0b5e8279a668c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
